### ISSUE TITLE
Progression

### ISSUE THREAD

**Issue by jackHedaya** [ATLauncher/ATLauncher-CLI#2]
Hello,

I was wondering if this repository is still being contributed to do or if there are any plans to do so as I was considering making an API for ATLauncher.

**Comment by RyanTheAllmighty** [comment]
There are no plans to continue this project for the time being. It may pick back up when ATLauncher Next is nearing release and there is a need for a cli.

**Comment by jackHedaya** [comment]
Great, thanks for the response.
